const BASE_KEYS={USER_SESSION:'student_dashboard_active_session',SCHEDULE_PREFIX:'student_dashboard_schedules_',TASKS_PREFIX:'student_dashboard_tasks_'};
const days=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'];
let currentUser=readJson(BASE_KEYS.USER_SESSION,null),schedules=[],tasks=[],activeDay=getTodayName(),taskFilter='all',taskSearch='',editingTaskId=null,editingScheduleId=null;

document.addEventListener('DOMContentLoaded',()=>{initClock();initNavigation();initAuth();initTaskManager();initScheduleManager();initMobileMenu();updateDayLabels();currentUser?showDashboard():showLoginOverlay();});
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function getTodayName(){return days[new Date().getDay()];}
function scheduleKey(){return currentUser?`${BASE_KEYS.SCHEDULE_PREFIX}${currentUser.id}`:'guest_schedules';}
function taskKey(){return currentUser?`${BASE_KEYS.TASKS_PREFIX}${currentUser.id}`:'guest_tasks';}
function saveData(){if(!currentUser)return;localStorage.setItem(scheduleKey(),JSON.stringify(schedules));localStorage.setItem(taskKey(),JSON.stringify(tasks));renderAll();}
function loadData(){schedules=readJson(scheduleKey(),[]);tasks=readJson(taskKey(),[]);renderAll();}

function initClock(){const clock=document.getElementById('liveClock'),date=document.getElementById('currentDate');const tick=()=>{const now=new Date();clock.textContent=now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})+' WIB';date.textContent=now.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});};tick();setInterval(tick,1000);}
function initNavigation(){document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{switchTab(btn.dataset.tab);document.querySelector('.sidebar')?.classList.remove('open');}));}
function switchTab(tab){document.querySelectorAll('.nav-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===tab));document.querySelectorAll('.tab-content').forEach(content=>content.classList.toggle('active',content.id===`tab-${tab}`));const titles={dashboard:'Selamat pagi',tasks:'Kelola pekerjaanmu.',schedule:'Jadwal yang teratur.',settings:'Ruang kerjamu.'};const title=document.getElementById('pageTitle');if(tab==='dashboard'&&currentUser)title.innerHTML=`Selamat pagi, <span id="headingName">${escapeHtml(currentUser.username.split(' ')[0])}</span>.`;else title.textContent=titles[tab]||'Orbit';}
function initMobileMenu(){document.getElementById('mobileMenuBtn')?.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));}

function initAuth(){const login=document.getElementById('loginDiscordBtn'),logout=document.getElementById('logoutBtn');const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('access_token')){fetchDiscordUserProfile(hash.get('access_token'));history.replaceState(null,'',location.pathname+location.search);}login.addEventListener('click',()=>{const cfg=DISCORD_CONFIG;location.href=`${cfg.AUTH_ENDPOINT}?client_id=${cfg.CLIENT_ID}&redirect_uri=${encodeURIComponent(cfg.REDIRECT_URI)}&response_type=token&scope=${cfg.SCOPES.join('%20')}`;});logout.addEventListener('click',()=>{if(confirm('Keluar dari akun ini?')){currentUser=null;localStorage.removeItem(BASE_KEYS.USER_SESSION);schedules=[];tasks=[];showLoginOverlay();}});}
function fetchDiscordUserProfile(token){fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${token}`}}).then(res=>{if(!res.ok)throw new Error('Discord API error');return res.json();}).then(data=>{currentUser={id:data.id,username:data.global_name||data.username,tag:data.discriminator&&data.discriminator!=='0'?`#${data.discriminator}`:'Discord',avatar:data.avatar?`https://cdn.discordapp.com/avatars/${data.id}/${data.avatar}.png`:'https://cdn.discordapp.com/embed/avatars/0.png'};localStorage.setItem(BASE_KEYS.USER_SESSION,JSON.stringify(currentUser));showDashboard();}).catch(()=>alert('Gagal mengambil profil Discord. Periksa koneksi atau konfigurasi OAuth2.'));}
function loginDemo(type){currentUser=type==='user_a'?{id:'demo_user_111',username:'Budi',tag:'#1234',avatar:'https://cdn.discordapp.com/embed/avatars/1.png'}:{id:'demo_user_222',username:'Siti',tag:'#5678',avatar:'https://cdn.discordapp.com/embed/avatars/2.png'};localStorage.setItem(BASE_KEYS.USER_SESSION,JSON.stringify(currentUser));showDashboard();}
function showLoginOverlay(){document.getElementById('loginOverlay').classList.add('active');}
function showDashboard(){document.getElementById('loginOverlay').classList.remove('active');document.getElementById('userAvatar').src=currentUser.avatar;document.getElementById('settingAvatar').src=currentUser.avatar;document.getElementById('userName').textContent=currentUser.username;document.getElementById('userTag').textContent=currentUser.tag;document.getElementById('pillAccountName').textContent=currentUser.username;document.getElementById('settingAccountName').textContent=currentUser.username;document.getElementById('settingAccountId').textContent=currentUser.id;document.getElementById('settingStorageKey').textContent=taskKey();switchTab('dashboard');loadData();}

function initTaskManager(){document.getElementById('openTaskModalBtn').addEventListener('click',()=>openTaskModal());document.getElementById('quickAddTaskBtn').addEventListener('click',()=>openTaskModal());closeModal('taskModal','closeTaskModal','cancelTaskModal');document.getElementById('taskForm').addEventListener('submit',saveTask);document.getElementById('taskSearch').addEventListener('input',event=>{taskSearch=event.target.value.toLowerCase().trim();renderTasks();});document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{taskFilter=btn.dataset.filter;document.querySelectorAll('.filter-btn').forEach(item=>item.classList.toggle('active',item===btn));renderTasks();}));}
function openTaskModal(task=null){editingTaskId=task?.id||null;document.getElementById('taskModalTitle').textContent=task?'Edit tugas':'Tugas baru';document.getElementById('taskId').value=task?.id||'';document.getElementById('taskTitle').value=task?.title||'';document.getElementById('taskCourse').value=task?.course||'';document.getElementById('taskPriority').value=task?.priority||'medium';document.getElementById('taskDeadline').value=task?.deadline||'';document.getElementById('taskNotes').value=task?.notes||'';openModal('taskModal');setTimeout(()=>document.getElementById('taskTitle').focus(),80);}
function saveTask(event){event.preventDefault();const value=id=>document.getElementById(id).value.trim();const record={id:editingTaskId||Date.now().toString(),title:value('taskTitle'),course:value('taskCourse'),priority:document.getElementById('taskPriority').value,deadline:document.getElementById('taskDeadline').value,notes:value('taskNotes'),completed:editingTaskId?Boolean(tasks.find(item=>item.id===editingTaskId)?.completed):false};tasks=editingTaskId?tasks.map(item=>item.id===editingTaskId?record:item):[...tasks,record];saveData();document.getElementById('taskModal').classList.remove('active');event.target.reset();editingTaskId=null;}
function toggleTask(id){tasks=tasks.map(task=>task.id===id?{...task,completed:!task.completed}:task);saveData();}
function deleteTask(id){if(confirm('Hapus tugas ini?')){tasks=tasks.filter(task=>task.id!==id);saveData();}}

function initScheduleManager(){document.getElementById('openScheduleModalBtn').addEventListener('click',()=>openScheduleModal());closeModal('scheduleModal','closeScheduleModal','cancelScheduleModal');document.getElementById('scheduleForm').addEventListener('submit',saveSchedule);document.querySelectorAll('.day-btn').forEach(btn=>btn.addEventListener('click',()=>{activeDay=btn.dataset.day;document.querySelectorAll('.day-btn').forEach(item=>item.classList.toggle('active',item===btn));renderSchedule();}));}
function openScheduleModal(schedule=null){editingScheduleId=schedule?.id||null;document.getElementById('scheduleModalTitle').textContent=schedule?'Edit jadwal':'Tambah jadwal';document.getElementById('scheduleId').value=schedule?.id||'';document.getElementById('schedSubject').value=schedule?.subject||'';document.getElementById('schedDay').value=schedule?.day||activeDay;document.getElementById('schedRoom').value=schedule?.room||'';document.getElementById('schedStartTime').value=schedule?.startTime||'';document.getElementById('schedEndTime').value=schedule?.endTime||'';document.getElementById('schedLecturer').value=schedule?.lecturer||'';openModal('scheduleModal');setTimeout(()=>document.getElementById('schedSubject').focus(),80);}
function saveSchedule(event){event.preventDefault();const value=id=>document.getElementById(id).value.trim();const record={id:editingScheduleId||Date.now().toString(),subject:value('schedSubject'),day:document.getElementById('schedDay').value,room:value('schedRoom'),startTime:document.getElementById('schedStartTime').value,endTime:document.getElementById('schedEndTime').value,lecturer:value('schedLecturer')};schedules=editingScheduleId?schedules.map(item=>item.id===editingScheduleId?record:item):[...schedules,record];activeDay=record.day;document.querySelectorAll('.day-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.day===activeDay));saveData();document.getElementById('scheduleModal').classList.remove('active');event.target.reset();editingScheduleId=null;}
function deleteSchedule(id){if(confirm('Hapus jadwal ini?')){schedules=schedules.filter(item=>item.id!==id);saveData();}}
function closeModal(modalId,...buttonIds){buttonIds.forEach(id=>document.getElementById(id)?.addEventListener('click',()=>{document.getElementById(modalId).classList.remove('active');}));document.getElementById(modalId).addEventListener('click',event=>{if(event.target.id===modalId)event.target.classList.remove('active');});}
function openModal(id){document.getElementById(id).classList.add('active');}

function renderAll(){renderTasks();renderSchedule();renderDashboard();renderSettings();}
function renderTasks(){const list=document.getElementById('taskList');let shown=tasks.filter(task=>taskFilter==='all'||(taskFilter==='pending'&&!task.completed)||(taskFilter==='done'&&task.completed));if(taskSearch)shown=shown.filter(task=>`${task.title} ${task.course}`.toLowerCase().includes(taskSearch));shown.sort((a,b)=>Number(a.completed)-Number(b.completed)||priorityRank(b.priority)-priorityRank(a.priority)||new Date(a.deadline)-new Date(b.deadline));if(!shown.length){list.innerHTML=`<div class="empty-state"><i class="fa-solid fa-sparkles"></i><p>${taskSearch?'Tidak ada tugas yang cocok.':'Belum ada tugas di daftar ini.'}</p></div>`;return;}list.innerHTML=shown.map(task=>`<article class="task-card ${task.completed?'completed':''}"><div class="task-header"><span class="badge badge-${task.priority}">${priorityLabel(task.priority)}</span><div><button class="delete-btn" onclick="openTaskModal(tasks.find(item=>item.id==='${task.id}'))" title="Edit tugas"><i class="fa-solid fa-pen"></i></button><button class="delete-btn" onclick="deleteTask('${task.id}')" title="Hapus tugas"><i class="fa-solid fa-trash"></i></button></div></div><h3 class="task-title ${task.completed?'is-completed':''}">${escapeHtml(task.title)}</h3><p class="task-course">${escapeHtml(task.course)}</p><p class="task-deadline"><i class="fa-regular fa-clock"></i> ${deadlineText(task.deadline)}</p>${task.notes?`<p class="task-notes">${escapeHtml(task.notes)}</p>`:''}<button class="btn ${task.completed?'btn-secondary':'btn-primary'} task-toggle" onclick="toggleTask('${task.id}')"><i class="fa-solid ${task.completed?'fa-rotate-left':'fa-check'}"></i> ${task.completed?'Tandai aktif':'Tandai selesai'}</button></article>`).join('');}
function renderSchedule(){const list=document.getElementById('scheduleList'),shown=schedules.filter(item=>item.day===activeDay).sort((a,b)=>a.startTime.localeCompare(b.startTime));if(!shown.length){list.innerHTML=`<div class="empty-state"><i class="fa-regular fa-calendar-xmark"></i><p>Belum ada jadwal untuk hari ${activeDay}.</p></div>`;return;}list.innerHTML=shown.map(item=>`<article class="sched-card"><div class="sched-time"><i class="fa-regular fa-clock"></i> ${escapeHtml(item.startTime)} - ${escapeHtml(item.endTime)}</div><h3 class="sched-title">${escapeHtml(item.subject)}</h3><div class="sched-detail"><i class="fa-solid fa-location-dot"></i>${escapeHtml(item.room)}</div><div class="sched-detail"><i class="fa-solid fa-user"></i>${escapeHtml(item.lecturer||'Dosen belum diisi')}</div><div class="card-tools"><button class="delete-btn" onclick="openScheduleModal(schedules.find(value=>value.id==='${item.id}'))" title="Edit jadwal"><i class="fa-solid fa-pen"></i></button><button class="delete-btn" onclick="deleteSchedule('${item.id}')" title="Hapus jadwal"><i class="fa-solid fa-trash"></i></button></div></article>`).join('');}
function renderDashboard(){const today=getTodayName(),todaySchedules=schedules.filter(item=>item.day===today).sort((a,b)=>a.startTime.localeCompare(b.startTime)),pending=tasks.filter(item=>!item.completed),done=tasks.filter(item=>item.completed),total=tasks.length,progress=total?Math.round(done.length/total*100):0;document.getElementById('statPendingTasks').textContent=pending.length;document.getElementById('statTodayClasses').textContent=todaySchedules.length;document.getElementById('statCompletedTasks').textContent=done.length;document.getElementById('statPendingHint').textContent=pending.length?`${pending.filter(item=>item.priority==='high').length} prioritas tinggi`:'Semua tugas aman';document.getElementById('statClassHint').textContent=todaySchedules.length?`${todaySchedules[0].startTime} mulai pertama`:'Jadwal masih kosong';document.getElementById('statCompletionHint').textContent=total?`${progress}% dari semua tugas`:'Mulai dari satu tugas';document.getElementById('navTaskCount').textContent=pending.length;document.getElementById('weekProgressLabel').textContent=`${progress}% selesai`;document.getElementById('weekProgressBar').style.width=`${progress}%`;renderNextClass(todaySchedules);renderPriority();renderWeek();}
function renderNextClass(items){const el=document.getElementById('nextClassContainer');if(!items.length){el.innerHTML=`<div class="empty-state"><i class="fa-regular fa-face-smile"></i><p>Tidak ada kelas hari ini. Waktunya fokus ke tugas.</p></div>`;return;}const item=items[0];el.innerHTML=`<div class="next-class"><div><span class="next-class-time">${escapeHtml(item.startTime)} - ${escapeHtml(item.endTime)}</span><h3>${escapeHtml(item.subject)}</h3><p><i class="fa-solid fa-location-dot"></i> ${escapeHtml(item.room)} ${item.lecturer?` · ${escapeHtml(item.lecturer)}`:''}</p></div><i class="fa-solid fa-arrow-right next-class-arrow"></i></div>`;}
function renderPriority(){const el=document.getElementById('priorityTaskList'),items=tasks.filter(task=>!task.completed&&task.priority==='high').slice(0,4);el.innerHTML=items.length?items.map(task=>`<li class="priority-item"><span class="priority-mark"></span><div><strong>${escapeHtml(task.title)}</strong><small>${escapeHtml(task.course)} · ${deadlineText(task.deadline)}</small></div><button class="btn-link" onclick="switchTab('tasks')">Buka</button></li>`).join(''):`<li class="empty-state"><i class="fa-solid fa-check"></i><p>Tidak ada prioritas tinggi.</p></li>`;}
function renderWeek(){const el=document.getElementById('weekDays');el.innerHTML=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'].map(day=>{const has=schedules.some(item=>item.day===day)||tasks.some(item=>new Date(item.deadline).toLocaleDateString('id-ID',{weekday:'long'})===day);return `<div class="week-day ${day===getTodayName()?'is-today':''} ${has?'has-task':''}"><b>${day.slice(0,3)}</b><span></span></div>`;}).join('');}
function renderSettings(){if(!currentUser)return;document.getElementById('settingStorageKey').textContent=taskKey();}
function updateDayLabels(){document.querySelectorAll('.day-btn small').forEach((el,index)=>el.textContent=String(index+1).padStart(2,'0'));document.querySelectorAll('.day-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.day===activeDay));}
function clearCurrentUserData(){if(!currentUser||!confirm(`Hapus semua jadwal dan tugas akun ${currentUser.username}?`))return;localStorage.removeItem(scheduleKey());localStorage.removeItem(taskKey());schedules=[];tasks=[];renderAll();alert('Semua data akun berhasil dihapus.');}
function priorityRank(value){return value==='high'?3:value==='medium'?2:1}function priorityLabel(value){return value==='high'?'Tinggi':value==='medium'?'Sedang':'Rendah'}function deadlineText(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return 'Tanpa tenggat';const overdue=!tasks.find(task=>task.deadline===value)?.completed&&date<new Date();return `${overdue?'Terlambat · ':''}${date.toLocaleDateString('id-ID',{day:'numeric',month:'short'})} ${date.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}`;}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}