const BASE_KEYS={USER_SESSION:'student_dashboard_active_session',SCHEDULE_PREFIX:'student_dashboard_schedules_',TASKS_PREFIX:'student_dashboard_tasks_'};
const days=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'];
let currentUser=readJson(BASE_KEYS.USER_SESSION,null),schedules=[],tasks=[],activeDay=getTodayName(),taskFilter='all',taskSearch='',editingTaskId=null,editingScheduleId=null,detailTaskId=null;
let supabaseClient=null,cloudMode=false;

document.addEventListener('DOMContentLoaded',()=>{initClock();initNavigation();initAuth();initTaskManager();initScheduleManager();initMobileMenu();updateDayLabels();currentUser?showDashboard():showLoginOverlay();});
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function getTodayName(){return days[new Date().getDay()];}
function scheduleKey(){return currentUser?`${BASE_KEYS.SCHEDULE_PREFIX}${currentUser.id}`:'guest_schedules';}
function taskKey(){return currentUser?`${BASE_KEYS.TASKS_PREFIX}${currentUser.id}`:'guest_tasks';}
function saveData(){if(!currentUser)return;localStorage.setItem(scheduleKey(),JSON.stringify(schedules));localStorage.setItem(taskKey(),JSON.stringify(tasks));renderAll();if(cloudMode)syncCloudData();}
async function loadData(){schedules=readJson(scheduleKey(),[]);tasks=readJson(taskKey(),[]);if(cloudMode){const cloudData=await loadCloudData();if(cloudData){schedules=cloudData.schedules;tasks=cloudData.tasks;localStorage.setItem(scheduleKey(),JSON.stringify(schedules));localStorage.setItem(taskKey(),JSON.stringify(tasks));}}renderAll();}
async function loadCloudData(){if(!supabaseClient||!currentUser)return null;const [taskResult,scheduleResult]=await Promise.all([supabaseClient.from('tasks').select('*').eq('user_id',currentUser.id),supabaseClient.from('schedules').select('*').eq('user_id',currentUser.id)]);if(taskResult.error||scheduleResult.error){console.error('Supabase load error',taskResult.error||scheduleResult.error);return null;}return{tasks:taskResult.data.map(task=>({id:task.id,title:task.title,course:task.course,priority:task.priority,deadline:toLocalInput(task.deadline),notes:task.notes||'',completed:task.completed,attachment:task.attachment||null})),schedules:scheduleResult.data.map(item=>({id:item.id,subject:item.subject,day:item.day,room:item.room,startTime:item.start_time,endTime:item.end_time,lecturer:item.lecturer||''}))};}
async function syncCloudData(){if(!supabaseClient||!currentUser)return;const taskRows=tasks.map(task=>({id:task.id,user_id:currentUser.id,title:task.title,course:task.course,priority:task.priority,deadline:task.deadline,notes:task.notes||'',completed:task.completed,attachment:task.attachment||{}}));const scheduleRows=schedules.map(item=>({id:item.id,user_id:currentUser.id,subject:item.subject,day:item.day,room:item.room,start_time:item.startTime,end_time:item.endTime,lecturer:item.lecturer||''}));const taskDelete=await supabaseClient.from('tasks').delete().eq('user_id',currentUser.id);const scheduleDelete=await supabaseClient.from('schedules').delete().eq('user_id',currentUser.id);if(taskDelete.error||scheduleDelete.error){console.error('Supabase delete error',taskDelete.error||scheduleDelete.error);return;}const inserts=[];if(taskRows.length)inserts.push(supabaseClient.from('tasks').insert(taskRows));if(scheduleRows.length)inserts.push(supabaseClient.from('schedules').insert(scheduleRows));const results=await Promise.all(inserts);const error=results.find(result=>result.error);if(error)console.error('Supabase save error',error.error);}

function initClock(){const clock=document.getElementById('liveClock'),date=document.getElementById('currentDate');const tick=()=>{const now=new Date();clock.textContent=now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})+' WIB';date.textContent=now.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});};tick();setInterval(tick,1000);}
function initNavigation(){document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{switchTab(btn.dataset.tab);document.querySelector('.sidebar')?.classList.remove('open');}));}
function switchTab(tab){document.querySelectorAll('.nav-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===tab));document.querySelectorAll('.tab-content').forEach(content=>content.classList.toggle('active',content.id===`tab-${tab}`));const titles={dashboard:'Selamat pagi',tasks:'Kelola pekerjaanmu.',schedule:'Jadwal yang teratur.',settings:'Ruang kerjamu.'};const title=document.getElementById('pageTitle');if(tab==='dashboard'&&currentUser)title.innerHTML=`Selamat pagi, <span id="headingName">${escapeHtml(currentUser.username.split(' ')[0])}</span>.`;else title.textContent=titles[tab]||'Orbit';}
function initMobileMenu(){document.getElementById('mobileMenuBtn')?.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));}

async function initAuth(){const login=document.getElementById('loginDiscordBtn'),logout=document.getElementById('logoutBtn');if(SUPABASE_CONFIG.ENABLED&&SUPABASE_CONFIG.URL&&SUPABASE_CONFIG.ANON_KEY&&window.supabase){supabaseClient=window.supabase.createClient(SUPABASE_CONFIG.URL,SUPABASE_CONFIG.ANON_KEY);const {data}=await supabaseClient.auth.getSession();if(data.session)applyCloudSession(data.session);supabaseClient.auth.onAuthStateChange((_event,session)=>{if(session)applyCloudSession(session);});}login.addEventListener('click',async()=>{if(!supabaseClient){alert('Supabase belum dikonfigurasi. Isi URL, anon key, dan ENABLED di config.js terlebih dahulu.');return;}const {error}=await supabaseClient.auth.signInWithOAuth({provider:'discord',options:{redirectTo:DISCORD_CONFIG.REDIRECT_URI}});if(error)alert(`Login Discord gagal: ${error.message}`);});logout.addEventListener('click',async()=>{if(!confirm('Keluar dari akun ini?'))return;if(supabaseClient&&cloudMode)await supabaseClient.auth.signOut();currentUser=null;cloudMode=false;localStorage.removeItem(BASE_KEYS.USER_SESSION);schedules=[];tasks=[];showLoginOverlay();});}
function applyCloudSession(session){const user=session.user,meta=user.user_metadata||{};currentUser={id:user.id,username:meta.full_name||meta.name||meta.user_name||user.email?.split('@')[0]||'Pengguna',tag:'Discord',avatar:meta.avatar_url||meta.picture||'https://cdn.discordapp.com/embed/avatars/0.png',provider:'discord'};cloudMode=true;localStorage.setItem(BASE_KEYS.USER_SESSION,JSON.stringify(currentUser));showDashboard();}
function loginDemo(type){currentUser=type==='user_a'?{id:'demo_user_111',username:'Budi',tag:'#1234',avatar:'https://cdn.discordapp.com/embed/avatars/1.png'}:{id:'demo_user_222',username:'Siti',tag:'#5678',avatar:'https://cdn.discordapp.com/embed/avatars/2.png'};localStorage.setItem(BASE_KEYS.USER_SESSION,JSON.stringify(currentUser));showDashboard();}
function showLoginOverlay(){document.getElementById('appContainer').classList.remove('ready');document.getElementById('loginOverlay').classList.add('active');}
function showDashboard(){document.getElementById('appContainer').classList.add('ready');document.getElementById('loginOverlay').classList.remove('active');document.getElementById('userAvatar').src=currentUser.avatar;document.getElementById('settingAvatar').src=currentUser.avatar;document.getElementById('userName').textContent=currentUser.username;document.getElementById('userTag').textContent=currentUser.tag;document.getElementById('pillAccountName').textContent=currentUser.username;document.getElementById('settingAccountName').textContent=currentUser.username;document.getElementById('settingAccountId').textContent=currentUser.id;document.getElementById('settingStorageKey').textContent=taskKey();document.getElementById('storageStatus').textContent=cloudMode?'Supabase cloud aktif':'Penyimpanan lokal aktif';document.getElementById('storageStatusHint').textContent=cloudMode?'Data tersinkron lintas browser dan perangkat.':'Data hanya tersedia di browser dan perangkat ini.';switchTab('dashboard');loadData();}

function initTaskManager(){document.getElementById('openTaskModalBtn').addEventListener('click',()=>openTaskModal());document.getElementById('quickAddTaskBtn').addEventListener('click',()=>openTaskModal());closeModal('taskModal','closeTaskModal','cancelTaskModal');closeModal('taskDetailModal','closeTaskDetailModal');document.getElementById('detailTaskEditBtn').addEventListener('click',()=>{const task=tasks.find(item=>item.id===detailTaskId);document.getElementById('taskDetailModal').classList.remove('active');if(task)openTaskModal(task);});document.getElementById('detailTaskToggleBtn').addEventListener('click',()=>{if(detailTaskId)toggleTask(detailTaskId);document.getElementById('taskDetailModal').classList.remove('active');});document.getElementById('taskForm').addEventListener('submit',saveTask);document.getElementById('taskFile').addEventListener('change',event=>{const file=event.target.files[0];document.getElementById('taskFileHint').textContent=file?`${file.name} · ${formatFileSize(file.size)}`:'Maksimal 10 MB. File tersimpan di Supabase Storage.';});document.getElementById('taskSearch').addEventListener('input',event=>{taskSearch=event.target.value.toLowerCase().trim();renderTasks();});document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{taskFilter=btn.dataset.filter;document.querySelectorAll('.filter-btn').forEach(item=>item.classList.toggle('active',item===btn));renderTasks();}));}
function openTaskModal(task=null){editingTaskId=task?.id||null;document.getElementById('taskModalTitle').textContent=task?'Edit tugas':'Tugas baru';document.getElementById('taskId').value=task?.id||'';document.getElementById('taskTitle').value=task?.title||'';document.getElementById('taskCourse').value=task?.course||'';document.getElementById('taskPriority').value=task?.priority||'medium';document.getElementById('taskDeadline').value=task?.deadline||'';document.getElementById('taskNotes').value=task?.notes||'';document.getElementById('taskFile').value='';document.getElementById('taskFileHint').textContent=task?.attachment?.name||'Maksimal 10 MB. File tersimpan di Supabase Storage.';openModal('taskModal');setTimeout(()=>document.getElementById('taskTitle').focus(),80);}
function openTaskDetails(task){if(!task)return;detailTaskId=task.id;const priority=document.getElementById('detailTaskPriority');priority.className=`badge badge-${task.priority}`;priority.textContent=priorityLabel(task.priority);document.getElementById('detailTaskTitle').textContent=task.title;document.getElementById('detailTaskCourse').textContent=task.course;document.getElementById('detailTaskDeadline').textContent=deadlineText(task.deadline);document.getElementById('detailTaskNotes').textContent=task.notes||'Tidak ada catatan.';document.getElementById('detailTaskStatus').textContent=task.completed?'Selesai':'Belum selesai';document.getElementById('detailTaskToggleBtn').innerHTML=`<i class="fa-solid ${task.completed?'fa-rotate-left':'fa-check'}"></i> ${task.completed?'Tandai aktif':'Tandai selesai'}`;document.getElementById('detailTaskAttachment').innerHTML=task.attachment?.name?`<a class="task-attachment" href="${escapeHtml(task.attachment.url||'#')}" target="_blank" rel="noopener"><i class="fa-solid fa-paperclip"></i>${escapeHtml(task.attachment.name)} <small>${formatFileSize(task.attachment.size)}</small></a>`:'Tidak ada lampiran.';openModal('taskDetailModal');}
async function saveTask(event){event.preventDefault();const value=id=>document.getElementById(id).value.trim();const file=document.getElementById('taskFile').files[0];if(file&&file.size>10*1024*1024){alert('Ukuran file maksimal 10 MB.');return;}const existing=tasks.find(item=>item.id===editingTaskId);const record={id:editingTaskId||Date.now().toString(),title:value('taskTitle'),course:value('taskCourse'),priority:document.getElementById('taskPriority').value,deadline:document.getElementById('taskDeadline').value,notes:value('taskNotes'),completed:existing?.completed||false,attachment:existing?.attachment||null};if(file){record.attachment=cloudMode?await uploadTaskFile(record.id,file):{name:file.name,size:file.size,type:file.type};}tasks=editingTaskId?tasks.map(item=>item.id===editingTaskId?record:item):[...tasks,record];saveData();document.getElementById('taskModal').classList.remove('active');event.target.reset();editingTaskId=null;}
async function uploadTaskFile(taskId,file){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${currentUser.id}/${taskId}/${Date.now()}-${safeName}`;const {error}=await supabaseClient.storage.from('task-files').upload(path,file,{upsert:true});if(error){alert(`Upload file gagal: ${error.message}`);return null;}const {data}=supabaseClient.storage.from('task-files').getPublicUrl(path);return{name:file.name,size:file.size,type:file.type,path,url:data.publicUrl};}
function toggleTask(id){tasks=tasks.map(task=>task.id===id?{...task,completed:!task.completed}:task);saveData();}
function deleteTask(id){if(confirm('Hapus tugas ini?')){tasks=tasks.filter(task=>task.id!==id);saveData();}}

function initScheduleManager(){document.getElementById('openScheduleModalBtn').addEventListener('click',()=>openScheduleModal());closeModal('scheduleModal','closeScheduleModal','cancelScheduleModal');document.getElementById('scheduleForm').addEventListener('submit',saveSchedule);document.querySelectorAll('.day-btn').forEach(btn=>btn.addEventListener('click',()=>{activeDay=btn.dataset.day;document.querySelectorAll('.day-btn').forEach(item=>item.classList.toggle('active',item===btn));renderSchedule();}));}
function openScheduleModal(schedule=null){editingScheduleId=schedule?.id||null;document.getElementById('scheduleModalTitle').textContent=schedule?'Edit jadwal':'Tambah jadwal';document.getElementById('scheduleId').value=schedule?.id||'';document.getElementById('schedSubject').value=schedule?.subject||'';document.getElementById('schedDay').value=schedule?.day||activeDay;document.getElementById('schedRoom').value=schedule?.room||'';document.getElementById('schedStartTime').value=schedule?.startTime||'';document.getElementById('schedEndTime').value=schedule?.endTime||'';document.getElementById('schedLecturer').value=schedule?.lecturer||'';openModal('scheduleModal');setTimeout(()=>document.getElementById('schedSubject').focus(),80);}
function saveSchedule(event){event.preventDefault();const value=id=>document.getElementById(id).value.trim();const record={id:editingScheduleId||Date.now().toString(),subject:value('schedSubject'),day:document.getElementById('schedDay').value,room:value('schedRoom'),startTime:document.getElementById('schedStartTime').value,endTime:document.getElementById('schedEndTime').value,lecturer:value('schedLecturer')};schedules=editingScheduleId?schedules.map(item=>item.id===editingScheduleId?record:item):[...schedules,record];activeDay=record.day;document.querySelectorAll('.day-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.day===activeDay));saveData();document.getElementById('scheduleModal').classList.remove('active');event.target.reset();editingScheduleId=null;}
function deleteSchedule(id){if(confirm('Hapus jadwal ini?')){schedules=schedules.filter(item=>item.id!==id);saveData();}}
function closeModal(modalId,...buttonIds){buttonIds.forEach(id=>document.getElementById(id)?.addEventListener('click',()=>{document.getElementById(modalId).classList.remove('active');}));document.getElementById(modalId).addEventListener('click',event=>{if(event.target.id===modalId)event.target.classList.remove('active');});}
function openModal(id){document.getElementById(id).classList.add('active');}

function renderAll(){renderTasks();renderSchedule();renderDashboard();renderSettings();}
function renderTasks(){const list=document.getElementById('taskList');let shown=tasks.filter(task=>taskFilter==='all'||(taskFilter==='pending'&&!task.completed)||(taskFilter==='done'&&task.completed));if(taskSearch)shown=shown.filter(task=>`${task.title} ${task.course}`.toLowerCase().includes(taskSearch));shown.sort((a,b)=>Number(a.completed)-Number(b.completed)||priorityRank(b.priority)-priorityRank(a.priority)||new Date(a.deadline)-new Date(b.deadline));if(!shown.length){list.innerHTML=`<div class="empty-state"><i class="fa-solid fa-sparkles"></i><p>${taskSearch?'Tidak ada tugas yang cocok.':'Belum ada tugas di daftar ini.'}</p></div>`;return;}list.innerHTML=shown.map(task=>`<article class="task-card ${task.completed?'completed':''}"><div class="task-header"><span class="badge badge-${task.priority}">${priorityLabel(task.priority)}</span><div><button class="delete-btn" onclick="openTaskModal(tasks.find(item=>item.id==='${task.id}'))" title="Edit tugas"><i class="fa-solid fa-pen"></i></button><button class="delete-btn" onclick="deleteTask('${task.id}')" title="Hapus tugas"><i class="fa-solid fa-trash"></i></button></div></div><h3 class="task-title ${task.completed?'is-completed':''}">${escapeHtml(task.title)}</h3><p class="task-course">${escapeHtml(task.course)}</p><p class="task-deadline"><i class="fa-regular fa-clock"></i> ${deadlineText(task.deadline)}</p>${task.attachment?.name?`<a class="task-attachment" href="${escapeHtml(task.attachment.url||'#')}" target="_blank" rel="noopener"><i class="fa-solid fa-paperclip"></i>${escapeHtml(task.attachment.name)} <small>${formatFileSize(task.attachment.size)}</small></a>`:''}${task.notes?`<p class="task-notes">${escapeHtml(task.notes)}</p>`:''}<button class="task-detail-link" onclick="openTaskDetails(tasks.find(item=>item.id==='${task.id}'))">Buka rincian <i class="fa-solid fa-arrow-right"></i></button><button class="btn ${task.completed?'btn-secondary':'btn-primary'} task-toggle" onclick="toggleTask('${task.id}')"><i class="fa-solid ${task.completed?'fa-rotate-left':'fa-check'}"></i> ${task.completed?'Tandai aktif':'Tandai selesai'}</button></article>`).join('');}
function renderSchedule(){const list=document.getElementById('scheduleList'),shown=schedules.filter(item=>activeDay==='all'||item.day===activeDay).sort((a,b)=>activeDay==='all'?(days.indexOf(a.day)-days.indexOf(b.day))||a.startTime.localeCompare(b.startTime):a.startTime.localeCompare(b.startTime));if(!shown.length){list.innerHTML=`<div class="empty-state"><i class="fa-regular fa-calendar-xmark"></i><p>${activeDay==='all'?'Belum ada jadwal kuliah.':`Belum ada jadwal untuk hari ${activeDay}.`}</p></div>`;return;}list.innerHTML=shown.map(item=>`<article class="sched-card"><div class="sched-time"><i class="fa-regular fa-clock"></i> ${activeDay==='all'?`${escapeHtml(item.day)} · `:''}${escapeHtml(item.startTime)} - ${escapeHtml(item.endTime)}</div><h3 class="sched-title">${escapeHtml(item.subject)}</h3><div class="sched-detail"><i class="fa-solid fa-location-dot"></i>${escapeHtml(item.room)}</div><div class="sched-detail"><i class="fa-solid fa-user"></i>${escapeHtml(item.lecturer||'Dosen belum diisi')}</div><div class="card-tools"><button class="delete-btn" onclick="openScheduleModal(schedules.find(value=>value.id==='${item.id}'))" title="Edit jadwal"><i class="fa-solid fa-pen"></i></button><button class="delete-btn" onclick="deleteSchedule('${item.id}')" title="Hapus jadwal"><i class="fa-solid fa-trash"></i></button></div></article>`).join('');}
function renderDashboard(){const today=getTodayName(),todaySchedules=schedules.filter(item=>item.day===today).sort((a,b)=>a.startTime.localeCompare(b.startTime)),pending=tasks.filter(item=>!item.completed),done=tasks.filter(item=>item.completed),total=tasks.length,progress=total?Math.round(done.length/total*100):0;document.getElementById('statPendingTasks').textContent=pending.length;document.getElementById('statTodayClasses').textContent=todaySchedules.length;document.getElementById('statCompletedTasks').textContent=done.length;document.getElementById('statPendingHint').textContent=pending.length?`${pending.filter(item=>item.priority==='high').length} prioritas tinggi`:'Semua tugas aman';document.getElementById('statClassHint').textContent=todaySchedules.length?`${todaySchedules[0].startTime} mulai pertama`:'Jadwal masih kosong';document.getElementById('statCompletionHint').textContent=total?`${progress}% dari semua tugas`:'Mulai dari satu tugas';document.getElementById('navTaskCount').textContent=pending.length;document.getElementById('weekProgressLabel').textContent=`${progress}% selesai`;document.getElementById('weekProgressBar').style.width=`${progress}%`;renderNextClass(todaySchedules);renderPriority();renderWeek();}
function renderNextClass(items){const el=document.getElementById('nextClassContainer');if(!items.length){el.innerHTML=`<div class="empty-state"><i class="fa-regular fa-face-smile"></i><p>Tidak ada kelas hari ini. Waktunya fokus ke tugas.</p></div>`;return;}const item=items[0];el.innerHTML=`<div class="next-class"><div><span class="next-class-time">${escapeHtml(item.startTime)} - ${escapeHtml(item.endTime)}</span><h3>${escapeHtml(item.subject)}</h3><p><i class="fa-solid fa-location-dot"></i> ${escapeHtml(item.room)} ${item.lecturer?` · ${escapeHtml(item.lecturer)}`:''}</p></div><i class="fa-solid fa-arrow-right next-class-arrow"></i></div>`;}
function renderPriority(){const el=document.getElementById('priorityTaskList'),items=tasks.filter(task=>!task.completed&&task.priority==='high').slice(0,4);el.innerHTML=items.length?items.map(task=>`<li class="priority-item"><span class="priority-mark"></span><div><strong>${escapeHtml(task.title)}</strong><small>${escapeHtml(task.course)} · ${deadlineText(task.deadline)}</small></div><button class="btn-link" onclick="switchTab('tasks')">Buka</button></li>`).join(''):`<li class="empty-state"><i class="fa-solid fa-check"></i><p>Tidak ada prioritas tinggi.</p></li>`;}
function renderWeek(){const el=document.getElementById('weekDays');el.innerHTML=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'].map(day=>{const has=schedules.some(item=>item.day===day)||tasks.some(item=>new Date(item.deadline).toLocaleDateString('id-ID',{weekday:'long'})===day);return `<div class="week-day ${day===getTodayName()?'is-today':''} ${has?'has-task':''}"><b>${day.slice(0,3)}</b><span></span></div>`;}).join('');}
function renderSettings(){if(!currentUser)return;document.getElementById('settingStorageKey').textContent=taskKey();}
function updateDayLabels(){document.querySelectorAll('.day-btn small').forEach((el,index)=>el.textContent=String(index+1).padStart(2,'0'));document.querySelectorAll('.day-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.day===activeDay));}
function clearCurrentUserData(){if(!currentUser||!confirm(`Hapus semua jadwal dan tugas akun ${currentUser.username}?`))return;localStorage.removeItem(scheduleKey());localStorage.removeItem(taskKey());schedules=[];tasks=[];renderAll();alert('Semua data akun berhasil dihapus.');}
function priorityRank(value){return value==='high'?3:value==='medium'?2:1}function priorityLabel(value){return value==='high'?'Tinggi':value==='medium'?'Sedang':'Rendah'}function deadlineText(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return 'Tanpa tenggat';const overdue=!tasks.find(task=>task.deadline===value)?.completed&&date<new Date();return `${overdue?'Terlambat · ':''}${date.toLocaleDateString('id-ID',{day:'numeric',month:'short'})} ${date.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}`;}
function toLocalInput(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return '';const pad=number=>String(number).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function formatFileSize(bytes){if(!bytes)return '0 B';const units=['B','KB','MB','GB'];const index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return `${(bytes/1024**index).toFixed(index?1:0)} ${units[index]}`;}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}